### ISSUE TITLE
Dependency problem with ActiveSupport > 3.0.9?

### ISSUE THREAD

**Issue by cimm** [morellon/rrd-ffi#11]
Sorry for spamming your issue list but think I found another problem. When I install the gem it installs the latest version of ActiveSupport as well as this is a dependency of the gem. No problem there if it wouldn't be for the new version of ActiveSupport. It installs 3.1.3 (at the time of writing) and that one doesn't seem to have the Time#advance method that is used in the gem. I downgraded ActiveSupport to 3.0.9 (as that's the stable version released before your last commit) and indeed, that one does not error out.

**Comment by morellon** [comment]
Hi cimm,

Sorry about that.
I will take a look at 3.1 and check what changed so we can use it.

**Comment by morellon** [comment]
Hi cimm,

Just released a new gem version. Can you check if this issue is ok now?
