### ISSUE TITLE
:start not working?

### ISSUE THREAD

**Issue by matejuh** [morellon/rrd-ffi#13]
I cant set start date. It is set to -24 hours.

This is working with rrdtool:

```rrdtool create target.rrd \

> ```
>      --start 1326067200 \
>      --step 86400 \
>      DS:mem:GAUGE:600:0:1001 \
>      RRA:LAST:0.5:1:10
> ```
> 
> ```
> ```

Produces:

```
rrdtool fetch target.rrd LAST --start 1326067200
                            mem

1326153600: -nan
1326240000: -nan
1326326400: -nan
1326412800: -nan
1326499200: -nan
1326585600: -nan
1326672000: -nan
1326758400: -nan
1326844800: -nan
```

How expected.

But RAW API:

```
RRD::Wrapper.create "myrrd.rrd","--start", "1326067200", "--step", "86400", "DS:values:GAUGE:172800:0:1001", "RRA:LAST:0.5:1:10"
```

Produces:

```
RRD::Wrapper.fetch "myrrd.rrd", "LAST"
=> [["time", "values"], [0, NaN]]
```

And DSLs:
```rrd.create :start => -10.days,  :step => 1.day do
ruby-1.9.2-p290 :124 >     datasource "values", :type => :gauge, :heartbeat => 2.days, :min => 0, :max => 1001
ruby-1.9.2-p290 :125?>   archive :last, :every => 1.day, :during => 11.days
ruby-1.9.2-p290 :126?>   end

``````

Produces:

``` rrd.fetch(:last).each {|line| puts line.inspect}
["time", "values"]
[1326672000, NaN]
[1326758400, NaN]
 => [["time", "values"], [1326672000, NaN], [1326758400, NaN]] 
``````

I thought Im using DSLs archive wrong, or thats problem in DSLs, but it looks like problem in something else.

Can you try it, please and check it?

//EDIT: Actually it looks like problem with fetch. Fetch from rrdtool displays expected values also from databases created with steps described upper.

**Comment by morellon** [comment]
Try using the DSL with:
   rrd.create :start => Time.now - 10.days, :step => 1.day
or
   rrd.create :start => 10.days.ago, :step => 1.day

 and tell me if it solves your issue.

**Comment by matejuh** [comment]
I didnt. But it really looks like problem with fetch.

I tried, what you adviced:

``` rrd = RRD::Base.new("bbb.rrd")
rrd.create :start => 10.days.ago, :step => 1.day do
ruby-1.9.2-p290 :151 >     datasource "values", :type => :gauge, :heartbeat => 2.days, :min => 0, :max => 1001
ruby-1.9.2-p290 :152?>   archive :last, :every => 1.day, :during => 10.days
ruby-1.9.2-p290 :153?>   end
 => true 

``````

Result:
``` rrd.fetch(:last).each {|line| puts line.inspect}
["time", "values"]
[1326672000, NaN]
[1326758400, NaN]
 => [["time", "values"], [1326672000, NaN], [1326758400, NaN]] 
``````

But rrdtool:

```
rrdtool fetch bbb.rrd LAST --start 1326153599
                         values

1326153600: -nan
1326240000: -nan
1326326400: -nan
1326412800: -nan
1326499200: -nan
1326585600: -nan
1326672000: -nan
1326758400: -nan
1326844800: -nan
```

**Comment by morellon** [comment]
Hi matejuh,

Thanks for your response. As you can notice, when calling from command line you set a start parameter for fetching.
The same behavior is expected when using the gem, otherwise we return the values since the last day.

rrd.fetch(:last, :start => 10.days.ago).each {|line| puts line.inspect}

Can you tell me if it works?

**Comment by matejuh** [comment]
Of course. That makes sence. Thank you. I have to start using your library more intuitively. Its working like a charm.
