### ISSUE TITLE
Option for using wrapper bang methods

### ISSUE THREAD

**Issue by kibs** [morellon/rrd-ffi#21]
I was debugging why my graphs didn't generate, and only after changing the Graph.save method to use the wrapper bang method, i got an error. Took my a while to figure out.

So maybe an option for turning on bang methods during development?

**Comment by morellon** [comment]
I don't see the point for that. Why couldn't you just use the bang method in your code and handle the exceptions?

**Comment by kibs** [comment]
doh, my bad, I didn't realize there was a RRD.graph! method :)

**Comment by morellon** [comment]
:) it's ok man. anyway, keep contributing and suggesting improvements. ;)
