### ISSUE TITLE
Opening an existing RRD

### ISSUE THREAD

**Issue by mikej165** [morellon/rrd-ffi#4]
Please pardon what must seem like a ridiculous question, but how does one open an existing RRD file? I can see how new ones are created, but what about rrds that are already there? I've been through the docs on this one can can't seem the find the answer.

Thanks.

**Comment by morellon** [comment]
It's never a ridiculous question. I will update the docs to make it more clear. 
;)
RRD::Base.new("path/to/file.rrd")

**Comment by mikej165** [comment]
I'm almost too embarrassed to say thank you. 8-)

**Comment by morellon** [comment]
;)
