### ISSUE TITLE
RRD database Archive with 1 year problem real number

### ISSUE THREAD

**Issue by marek-vanco** [morellon/rrd-ffi#5]
Hello, Excuse me, I have a question:

When I create a new database like;

  @rrd.create :start => Time.now.utc - 1.hour, :step => 20.minutes do
        datasource 'temp_c', :type => :gauge, :heartbeat => 30.minutes, :min => -70, :max => 50
        datasource 'humidity', :type => :gauge, :heartbeat => 30.minutes, :min => 0, :max => 100
        datasource 'pressure', :type => :gauge, :heartbeat => 30.minutes, :min => 850, :max => 1100
        archive :average, :every => 20.minutes, :during => 1.day
        archive :average, :every => 1.day, :during => 1.month
        archive :average, :every => 1.week, :during => 1.years

Builder function return:

"DS:temp_c:GAUGE:1800:-70:50"
"DS:humidity:GAUGE:1800:0:100"
"DS:pressure:GAUGE:1800:850:1100"
"RRA:AVERAGE:0.5:1:72"
"RRA:AVERAGE:0.5:72:30"
"RRA:AVERAGE:0.5:504:52.17857142857143"

Or, I my opinion,  RRA can't have real number (52.17857142857143 value.)
with option 
archive :average, :every => 1.week, :during => 365.days 
there isn't problem with value.

I don't know why, but in ruby:
ruby-1.9.2-p136 :159 > 1.years/365.days
 => 1.0006849315068493 

Is there need add "to_i" in Builder class to avoid this phenomen? Like:

```
  archive = "RRA:#{consolidation_function.to_s.upcase}:0.5:#{archive_steps.to_i}:#{archive_rows.to_i}"
```

Please exuce my my english, and I'm newbe in Ruby...
Thanks you for rrd-ffi, thanks you for reading.

**Comment by morellon** [comment]
Hi alpyapple,

You're right. RRA only accepts integers, so I will need to use the to_i method.
A fix you could use in your case until I add the to_i to the code is 52.weeks, instead of 1.year.

I will check the year method in active support to know why it isn't 365 days.
Don't bother the english, I'm not an american my self, and welcome to the language.
;)

I will get back in touch soon

**Comment by morellon** [comment]
I finally added the to_i to force steps and rows as integer in the RRA.
It is in the latest version of rrd-ffi.

Thanks for contributing!
